mkosi.conf.d/20-fedora/mkosi.extra/usr/lib/tmpfiles.d/etc-authselect.conf
mkosi.extra/usr/lib/tmpfiles.d/etc.conf
mkosi.postinst.chroot

Minor commits to add/adjust tmpfiles.d symlinks under `/etc`, and to restrict the sed file modification in `mkosi.postinst.chroot` to only run if the files exist.

Several minor fixes to get fedora-based build working

---

mkosi.extra/usr/lib/tmpfiles.d/etc.conf

These are different between Arch and Fedora so make them both conditional.

Conditionalize more tmpfiles entries

---

mkosi.extra/usr/lib/tmpfiles.d/etc.conf

Among other things, this is needed for `systemd-resolved` to work on Fedora.

Add crypto-policies to tmpfiles

---

mkosi.clean

This should make things easier if someone sets `ImageId` in their local config.

Use $IMAGE_ID in mkosi.clean instead of hardcoding

---

mkosi.profiles/desktop/mkosi.conf
mkosi.profiles/desktop/mkosi.conf.d/arch/mkosi.conf
mkosi.profiles/desktop/mkosi.conf.d/fedora/mkosi.conf

- add support for alsa and pulseaudio clients in pipewire
- install alsa sof firmware
- install kernel-modules on Fedora (which includes all the sound kmods, among other things)

desktop: add missing packages to get sound working

---

mkosi.extra/usr/lib/systemd/system-preset/10-particleos.preset
mkosi.extra/usr/lib/systemd/system/preset-global.service

`preset-global.service` was never run, which resulted in user presets never getting created. Wire it up to sysinit to ensure it's run and fix its dependencies while at it.

Fix ordering cycle between preset-global.service and basic.target

---

mkosi.extra/usr/lib/systemd/system-preset/10-particleos.preset

Restore accidentally dropped preset, fixup for #9

fixup: Fix ordering cycle between preset-global.service and basic.target

---

mkosi.images/netesp/mkosi.conf
mkosi.images/netesp/mkosi.conf.d/arch.conf
mkosi.images/netesp/mkosi.conf.d/fedora.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-debian-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/loader.conf

This makes #20 work.
Also adds a commit on top, which adds a menu entry pointing to @bluca's Debian ParticleOS build.
You can build this and then run `systemd-vmspawn -n --register=no -i mkosi.build/netesp.img.raw` and it works beautifully. Will use network for getting the UKI (i.e. stage 2), but not for the netesp (stage 1). That can be made work too, but is more complicated: just boot any regular mkosi image one can log into and do `kernel-bootcfg --add-url=… --title=foobar --once && reboot` pointing it to a http url with the netesp image, and it will then go through the full chain: state 1 and stage 2 both acquired via http.

working netsp support

---

mkosi.postinst.chroot

Fedora disables the userdb tmpfiels snippet by default, but we want it enabled in particleos images, so symlink it to the proper name to enable it.

Symlink example userdb tmpfiles snippet if available

---

mkosi.conf

Let's make visible what this is, and name the hosts "particle"

mkosi: set host name to "particle"

---

mkosi.conf

This depends on https://github.com/systemd/systemd/pull/36647
This gives every instance of ParticleOS a slightly different hostname (well, within the bounds of 2^32), which is quite useful when operating with a number of them.

mkosi: tweak default hostname choice

---

TODO
mkosi.conf
mkosi.uki-profiles/10-live.conf
mkosi.uki-profiles/80-storagetm.conf
mkosi.uki-profiles/90-factory-reset.conf
mkosi.uki-profiles/91-factory-reset-with-tpm-clear.conf
mkosi.uki-profiles/95-emergency.conf
mkosi.uki-profiles/99-debug.conf

91-factory-reset-with-tpm-clear.conf + 80-storagetm.conf → disallow all use of the various partitions
default + 90-factory-reset.conf + 95-emergency.conf + 99-debug.conf → require verity on usr, require encryption on root fs, mount home, use swap, ignore rest
10-live.conf → require verity on usr, ignore rest

enforce image policy

---

mkosi.extra/usr/lib/repart.d/30-swap.conf
mkosi.extra/usr/lib/repart.d/40-root.conf
mkosi.extra/usr/lib/repart.d/50-home.conf

Let's associate these directories with our image. In a world where these partitions are TPM locked it really matters we unlock them with the right OS, because unlocking is unlikely to be possible on other images since their PCRs won't match.
This is just preparation for an unknown, bright future. I have nothing in petto that would actually care about the names at this point.

repart: include image name in home/swap/root

---

mkosi.conf
mkosi.uki-profiles/10-live.conf
mkosi.uki-profiles/90-factory-reset.conf
mkosi.uki-profiles/95-emergency.conf
mkosi.uki-profiles/99-debug.conf

Let's make the image policy stricter: we want to require signed veritfy, not just plain verity logic when we dissect the root fs.
Note that currently this part of the image policy is not enforced either way, but this is going to change soon (I hope).
Follow-up for: 03569f9f85ea45cf1176b6e3d78916ffffcc8e73

image-policy: tighten policy, insist on signing

---

mkosi.conf
mkosi.uki-profiles/10-live.conf
mkosi.uki-profiles/80-storagetm.conf
mkosi.uki-profiles/90-factory-reset.conf
mkosi.uki-profiles/91-factory-reset-with-tpm-clear.conf
mkosi.uki-profiles/95-emergency.conf
mkosi.uki-profiles/99-debug.conf

This is a companion to https://github.com/systemd/systemd/pull/36631, and switch particleos over to mounting the root fs via the dissection logic, i.e. taking the image policy into account.

switch to "root=dissect"

---

mkosi.conf

The issue is fixed in main:
https://github.com/systemd/systemd/pull/37434
This reverts commit 05aa606c542318892a7307da1d42ce14c1e6cf55.

Revert "Temporarily mask systemd-validatefs@.service"

---

mkosi.extra/usr/lib/systemd/network/89-ethernet.network
mkosi.extra/usr/lib/systemd/system-preset/10-particleos.preset
mkosi.profiles/desktop/mkosi.conf

Ensure we get networking by default in the minimal image by enabling networkd's config.
Given it now conflicts with NetworManager, disable networkd in the desktop profile via presets.

Enable wired interfaces by default in networkd, disable in desktop profile

---

mkosi.conf.d/debian/mkosi.postinst.chroot

On Debian there are custom patches that break /usr/lib/pam.d/ so login doesn't work:
Aug 28 17:52:55 particle-6579-bbfd login[1260]: PAM _pam_load_conf_file: unable to open config for /etc/pam.d/common-auth
Aug 28 17:52:55 particle-6579-bbfd login[1261]: PAM _pam_load_conf_file: unable to open config for /etc/pam.d/common-auth
Aug 28 17:52:55 particle-6579-bbfd login[1260]: PAM error loading (null)
Aug 28 17:52:55 particle-6579-bbfd login[1261]: PAM error loading (null)
Aug 28 17:52:55 particle-6579-bbfd login[1260]: PAM _pam_init_handlers: error reading /usr/lib/pam.d/login
Aug 28 17:52:55 particle-6579-bbfd login[1261]: PAM _pam_init_handlers: error reading /usr/lib/pam.d/login
Aug 28 17:52:55 particle-6579-bbfd login[1261]: PAM _pam_init_handlers: [Critical error - immediate abort]
Aug …

debian: drop debian-specific pam.d line from tmpfiles.d

---

mkosi.profiles/gnome/mkosi.conf.d/debian/mkosi.conf
mkosi.profiles/gnome/mkosi.extra/usr/lib/systemd/system/homed-accounts-workaround.service

Needed until https://gitlab.freedesktop.org/accountsservice/accountsservice/-/issues/89 is fixed to let GNOME know that homed users exist and there's no need to run the initial user setup.
Install the initial setup package so that if someone doesn't create a user ahead of time there's a nice GUI for it.

gnome: add workaround for accountsservices and enable gnome-initial-setup

---

mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-debian-13-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-debian-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-debian-testing-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-fedora-41-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-fedora-42-particleos-obs-current.conf
mkosi.images/netesp/mkosi.extra/efi/loader/entries/90-fedora-rawhide-particleos-obs-current.conf

F41 was removed and F42 was added.
Deb13 was added. Rename testing to include 'testing' in the name

UKI: update remote images

---

mkosi.profiles/desktop/mkosi.conf

Make clipboard and other niceties work out of the box. Won't run on hardware anyway as it's typically tied to virtio udev rules.

desktop: install qemu-guest-agent
